/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package Wheatley;

import java.util.ArrayList;
import java.util.List;
import org.pircbotx.Colors;
import org.pircbotx.hooks.ListenerAdapter;
import org.pircbotx.hooks.events.MessageEvent;

/**
 *
 * @author Steve-O
 * Quotes from Portal 2's Cave Johnson
 * http://theportalwiki.com/wiki/Cave_Johnson_voice_lines
 * http://www.cavejohnsonhere.com/
 */
public class CaveJohnson extends ListenerAdapter {
    List<String> a = null;
    
    public void onMessage(MessageEvent event) {
        String message = Colors.removeFormattingAndColors(event.getMessage());
        String[] messageArray = Colors.removeFormattingAndColors(event.getMessage()).split(" ");
        if ((message.equalsIgnoreCase("Cave Johnson"))||(message.equalsIgnoreCase("!cave"))||message.equalsIgnoreCase("cave johnson here")) {
            if (a == null) {
                a = getQuoteList();
            }
            String quote = a.get((int) (Math.random()*a.size()-1));
            event.getBot().sendIRC().message(event.getChannel().getName(),quote);
        }
    }
    
    public ArrayList<String> getQuoteList() {
        ArrayList<String> a = new ArrayList<String>();
//1952
        a.add("Welcome, gentlemen, to Aperture Science. Astronauts, war heroes, Olympians--you're here because we want the best, and you are it. So: Who is ready to make some science?");
        a.add("Now, you already met one another on the limo ride over, so let me introduce myself.");
        a.add("I'm Cave Johnson. I own the place.");
        a.add("That eager voice you heard is the lovely Caroline, my assistant. Rest assured, she has transferred your honorarium to the charitable organization of your choice. Isn't that right, Caroline?");
        a.add("She's the backbone of this facility. Pretty as a postcard, too. Sorry, fellas. She's married. To science.");
        a.add("There's a thousand tests performed every day here in our enrichment spheres. I can't personally oversee every one of them, so these pre-recorded messages'll cover any questions you might have, and respond to any incidents that may occur in the course of your science adventure.");
        a.add("Your test assignment will vary, depending on the manner in which you have bent the world to your will.");
        a.add("Those of you helping us test the repulsion gel today, just follow the blue line on the floor.");
        a.add("Those of you who volunteered to be injected with praying mantis DNA, I've got some good news and some bad news.");
        a.add("Bad news is we're postponing those tests indefinitely. Good news is we've got a much better test for you: Fighting an army of mantis men. Pick up a rifle and follow the yellow line. You'll know when the test starts.");
        a.add("They say great science is built on the shoulders of giants. Not here. At Aperture, we do all our science from scratch. No hand holding.");
//1953
        a.add("Alright, let's get started. This first test involves something the lab boys call 'repulsion gel.'");
        a.add("You're not part of the control group, by the way. You get the gel. Last poor son of a gun got blue paint. Hahaha. All joking aside, that did happen - broke every bone in his legs. Tragic. But informative. Or so I'm told.");
        a.add("The lab boys just informed me that I should not have mentioned the control group. They're telling me I oughtta stop making these pre-recorded messages. That gave me an idea: Make more pre-recorded messages. I pay the bills here, I can talk about the control group all damn day.");
        a.add("For this next test, we put nanoparticles in the gel. In layman's terms, that's a billion little gizmos that are gonna travel into your bloodstream and pump experimental genes and RNA molecules and so forth into your tumors.");
        a.add("Now, maybe you don't have any tumors. Well, don't worry. If you sat on a folding chair in the lobby and weren't wearing lead underpants, we took care of that too.");
        a.add("Oh, in case you got covered in that repulsion gel, here's some advice the lab boys gave me: DO NOT get covered in the repulsion gel.");
        a.add("We haven't entirely nailed down what element it is yet, but I'll tell you this: It's a lively one, and it does NOT like the human skeleton.");
//1957
        a.add("All these science spheres are made of asbestos, by the way. Keeps out the rats. Let us know if you feel a shortness of breath, a persistent dry cough or your heart stopping. Because that's not part of the test. That's asbestos.");
        a.add("Good news is, the lab boys say the symptoms of asbestos poisoning show a median latency of forty-four point six years, so if you're thirty or older, you're laughing. Worst case scenario, you miss out on a few rounds of canasta, plus you forwarded the cause of science by three centuries. I punch those numbers into my calculator, it makes a happy face.");
        a.add("Ha! I like your style. You make up your own rules, just like me.");
        a.add("Bean counters said I couldn't fire a man just for being in a wheelchair. Did it anyway. Ramps are expensive.");
        a.add("Just a heads-up: That coffee we gave you earlier had fluorescent calcium in it so we can track the neuronal activity in your brain. There's a slight chance the calcium could harden and vitrify your frontal lobe. Anyway, don't stress yourself thinking about it. I'm serious. Visualizing the scenario while under stress actually triggers the reaction.");
//1958
        a.add("Now, if you're part of Control Group Kepler-Seven, we implanted a tiny microchip about the size of a postcard into your skull. Most likely you've forgotten it's even there, but if it starts vibrating and beeping during this next test, let us know, because that means it's about to hit five hundred degrees, so we're gonna need to go ahead and get that out of you pretty fast.");
        a.add("I'm telling 'em, keep your pants on.");
        a.add("Alright, this next test may involve trace amounts of time travel. So, word of advice: If you meet yourself on the testing track, don't make eye contact. Lab boys tell me that'll wipe out time. Entirely. Forward and backward! So do both of yourselves a favor and just let that handsome devil go about his business.");
        a.add("If you're hearing this, it means you're taking a long time on the catwalks between tests. The lab boys say that might be a fear reaction.");
        a.add("I'm no psychiatrist, but coming from a bunch of eggheads who wouldn't recognize the thrill of danger if it walked up and snapped their little pink bras, that sounds like 'projection'.");
        a.add("THEY didn't fly into space, storm a beach, or bring back the gold. No sir, we did! It's you and me against the world, son! I like your grit! Hustle could use some work, though. Now let's solve this thing!");
        a.add("Science isn't about WHY. It's about WHY NOT. Why is so much of our science dangerous? Why not marry safe science if you love it so much. In fact, why not invent a special safety door that won't hit you on the butt on the way out, because you are fired.");
//        a.add("Not you, test subject, you're doing fine.");
        a.add("Yes, you. Box. Your stuff. Out the front door. Parking lot. Car. Goodbye.");
//1959
        a.add("Congratulations! The simple fact that you're standing here listening to me means you've made a glorious contribution to science.");
        a.add("As founder and CEO of Aperture Science, I thank you for your participation and hope we can count on you for another round of tests.");
        a.add("We're not gonna release this stuff into the wild until it's good and damn ready, so as long as you keep yourself in top physical form, there'll always be a limo waiting for you.");
//        a.add("Say goodbye, Caroline.");
//        a.add("She is a gem.");
//1971
        a.add("Greetings, friend. I'm Cave Johnson, CEO of Aperture Science - you might know us as a vital participant in the 1968 Senate Hearings on missing astronauts. And you've most likely used one of the many products we invented. But that other people have somehow managed to steal from us. Black Mesa can eat my bankrupt--");
        a.add("Right. Now, you might be asking yourself, 'Cave, just how difficult are these tests? What was in that phone book of a contract I signed? Am I in danger?' Let me answer those questions with a question: Who wants to make sixty dollars? Cash.");
        a.add("You can also feel free to relax for up to 20 minutes in the waiting room, which is a damn sight more comfortable than the park benches most of you were sleeping on when we found you.");
        a.add("So. Welcome to Aperture. You're here because we want the best, and you're it. Nope. Couldn't keep a straight face.");
        a.add("Anyway, don't smudge up the glass down there. In fact, why don't you just go ahead and not touch anything unless it's test related.");
//1972
        a.add("The testing area's just up ahead. The quicker you get through, the quicker you'll get your sixty bucks.");
        a.add("Caroline, are the compensation vouchers ready?");
        a.add("Great job, astronaut, war hero, and/or Olympian! With your help, we're gonna (tape sped up) change the world!");
        a.add("This on? [thump thump] Hey. Listen up down there. That thing's called an elevator. Not a bathroom.");
//1976
        a.add("If you're interested in an additional sixty dollars, flag down a test associate and let 'em know. You could walk out of here with a hundred and twenty weighing down your bindle if you let us take you apart, put some science stuff in you, then put you back together good as new.");
        a.add("In case you're interested, there's still some positions available for that bonus opportunity I mentioned earlier. Again: All you gotta do is let us disassemble you. We're not banging rocks together here. We know how to put a man back together.");
        a.add("So that's a complete reassembly. New vitals. Spit-shine on the old ones. Plus we're scooping out tumors. Frankly, you oughtta be paying us.");
//1978
        a.add("Thank you - I can't believe I'm thanking these people - for staggering your way through Aperture Science's propulsion gel testing. You've made some real contributions to society for a change, and for that, humanity is grateful.");
        a.add("If you had any belongings, please pick them up now. We don't want old newspapers and sticks cluttering up the building.");
        a.add("For many of you, I realize 60 dollars is an unprecedented windfall, so don't go spending it all on... I don't know. Caroline, what do these people buy? Tattered hats? Beard dirt?");
//1981
//        a.add("Welcome to the enrichment center. [cough]");
        a.add("Since making test participation mandatory for all employees, the quality of our test subjects has risen dramatically. Employee retention, however, has not.");
        a.add("[cough] As a result, you may have heard we're gonna phase out human testing. There's still a few things left to wrap up, though.");
        a.add("The bean counters told me we literally could not afford to buy seven dollars worth of moon rocks, much less seventy million. Bought 'em anyway. Ground 'em up, mixed em into a gel. And guess what? Ground up moon rocks are pure poison. I am deathly ill.");
        a.add("Still, it turns out they're a great portal conductor. So now we're gonna see if jumping in and out of these new portals can somehow leech the lunar poison out of a man's bloodstream. When life gives you lemons, make lemonade. [coughs] Let's all stay positive and do some science.");
        a.add("That said, I would really appreciate it if you could test as fast as possible. Caroline, please bring me more pain pills.");
//1982
        a.add("All right, I've been thinking. When life gives you lemons? Don't make lemonade. Make life take the lemons back! Get mad! 'I don't want your damn lemons! What am I supposed to do with these?' Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am? I'm the man who's going to burn your house down! With the lemons! I'm going to get my engineers to invent a combustible lemon that burns your house down! [cough]");
        a.add("The point is: If we can store music on a compact disc, why can't we store a man's intelligence and personality on one? So I have the engineers figuring that out now.");
        a.add("Brain Mapping. Artificial Intelligence. We should have been working on it thirty years ago. I will say this - and I'm gonna say it on tape so everybody hears it a hundred times a day: If I die before you people can pour me into a computer, I want Caroline to run this place. Now she'll argue. She'll say she can't. She's modest like that. But you make her. Hell, put her in my computer. I don't care.");
        a.add("Allright, test's over. You can head on back to your desk.");
//Intercom Messages
//1952
        a.add("If you've cut yourself at all in the course of these tests, you might have noticed that your blood is pure gasoline. That's normal. We've been shooting you with an invisible laser that's supposed to turn blood into gasoline, so all that means is, it's working.");
        a.add("If you need to go to the bathroom after this next series of tests, please let a test associate know, because in all likelihood, whatever comes out of you is going to be coal. Only temporary, so do not worry. If it persists for a week, though, start worrying and come see us, because that's not supposed to happen.");
        a.add("Just a heads up: We're gonna have a superconductor turned up full blast and pointed at you for the duration of this next test. I'll be honest, we're throwing science at the wall here to see what sticks. No idea what it'll do. Probably nothing. Best-case scenario, you might get some superpowers. Worst case, some tumors, which we'll cut out.");
//1971
        a.add("If you're allergic to peanuts, you might want to tell somebody now, because this next test may turn your blood into peanut water for a few minutes. On the bright side, if we can make this happen, they're gonna have to invent a new type of Nobel Prize to give us, so hang in there.");
        a.add("The average human male is about sixty percent water. Far as we're concerned, that's a little extravagant. So if you feel a bit dehydrated in this next test, that's normal. We're gonna hit you with some jet engines, and see if we can't get you down to twenty or thirty percent.");
        a.add("All right. We're working on a little teleportation experiment. Now, this doesn't work with all skin types, so try to remember which skin is yours, and if it doesn't teleport along with you, we'll do what we can to sew you right back into it.");
//perpetual testing initiative
        a.add("Welcome, test subject, it's Cave. Prime. From Earth One. I am speaking to you from across time and space! I am literally in the future! I am--Hold on... [off mic] What? [on mic] Alright, my assistant Greg tells me none of that's true. Got excited. You are the first test subject we have ever sent into a parallel universe, which apparently has nothing to do with time travel. Still exciting. Anyway, you should be seeing a test chamber in front of you. We designed it, those backwater universe yokels built it, and you're gonna test it. Remember: You gotta let us know if it WORKS or not, otherwise you're wasting everybody's time on two earths. Alright, get to it.");
        a.add("Cave here. Just so you know, this mic isn't two way. Can't hear a damn thing you're saying, so don't waste any oxygen trying to talk. [off mic] What? [on mic] My assistant Greg says some of these alternate Earths may not have oxygen. The air might be nitrogen or methane or, hell, everybody's head might be inside out. So just take little itty bitty breaths and if anybody asks you why your head's inside out, remember it's only inside out from their perspective, and you're fine. Head-wise. Trouble-wise, you're in a lot of it and you should probably run. Alright, enough hypotheticals. Let's test this test!");
        a.add("Cave here. Man oh man. Wow. Greg's multiple universe theory was dicey, but you're pulling through with flying colors. We're all very proud of Greg... Oh, and you.");
        a.add("Before we start testing today, let's have our mandatory minute of silence in honor of Earth's governing body, the Sentient Cloud. [throat clear] Starting now... [coughing] ...... [more coughing] ......... Good, right. All ha il the sentient cloud. Begin testing.");
        a.add("I've just been notified that one of our test subjects may have angered the Sentient Cloud by beginning testing early. Now, as you all know, the cloud has banned all camera technology--hates getting its picture taken. So this'll have to be on the honor system: Will whoever started testing early please go outside so they can be consumed by the Cloud.");
        a.add("Just a heads-up that the Cloud's still waiting. I don't think that thing's gonna go away, so somebody might wanna get out there.");
        a.add("No! No! It came in under the door! It's leeching off all my skin! Aghhhhh- [click] Excerpt there from one of our safety videos. Grisly stuff, very informative. Somebody doesn't get out there soon we're gonna have to have a lottery, because believe me, if we keep that cloud waiting much longer he's coming in under the doors, and he will leech off all of our skin.");
        a.add("Cave here. The real Cave. Greg's been crunching some numbers here on Earth Prime. Turns out, the likelihood of me being the only Cave who likes talking to test subjects is-- [off mic] What's the actual number, Greg? [on mic] Right. Zero. So tell you what, we're gonna use a code word. If I say chariots, it means you're listening to me. Otherwise, it's an imposter Cave. I want you to know, you have a license to kill on this one. [off mic] What? [on mic] Greg says that might destroy the entire multiverse. Point is, use your own judgement. License-to-kill.");
        a.add("Welcome, gentlemen, to Aperture Rituals. Astronauts, war heroes, olympians: you're here because of an ancient mating ritual etched in a monolith by the Elder Monks to forestall the end of days. So, who is ready to make love to a giant bird?");
        a.add("Cave Johnson here. Just wanna let the cafeteria staff know to lay off the soylent green. I'm holding a memo from the President, and it turns out that soylent green is... [paper rustling] let's see here... doubling in price. Now listen up: I don't care how good people tastes. This stuff's costing me more than lobster, so we're going back to fishsticks.");
        a.add("(tap dancing noises) Hey. It's Cave. Someone's not daaaancing. Come on. You know the law - testing IS NOT a dance exemption. Don't make me call the dance police.");
        a.add("Test subject, can you hear me? Congratulations! You are the world's first half-man, half-machine police officer! Well, first batch. There was a pretty big shootout. Bought all your caracasses off the mayor. Anyway, you should be proud to be a part of Aperture's android law enforcement initiative. Or, as someone who's good at naming things, i.e. me, would call it, ROBO -- No. Robot-a-Cop! Oh, that's much better. Now, before we get you solving crimes, we gotta getcha to solve this test. Promised the mayor I'd make sure you weren't all unstable potatoheads before I gave you all guns.");
        a.add("Come in, Robot-a-Cop! It's your chief. First: You're a damn good cop. Second: You're a loose cannon. Alright, that's probably enough motivation. Oh, before I forget! Greg tells me you might be getting some tragic flashbacks of your former life. Don't sweat it, those aren't yours. Due to a software problem, that's a real-time feed of Greg's current life. He's a sad little man. Anyway, just try to ignore him.");
        a.add("Cave here. Chariots. Just a heads up: If it seems like you're walking faster than light, you're probably in a universe where light doesn't haul nearly as much ass as it does on Earth One. The lab boys say if you insist on walking faster than light, you are one hundred percent going to go back in time. How far? Far enough to meet your great great grandfather and tell him you're fired. Because guess what? I'll let you finish that thought.");
        a.add("Welcome, test prisoner, to the Terra-Three penal science colony. Space criminals, political prisoners, exiled planetary leaders: You're here because the galaxy needed a place to put you, and this is it. So, who is ready to stay here until they die? Now, you already met one another on the hyperdrive over, so let me introduce myself. I'm Cave Johnson. I'm the warden around here.");
        a.add("Attention, test prisoners attempting to escape through the air ducts. I don't know what nonsense you learned on TV, but in real life, air ducts just go to the air conditioning unit. It's also pretty dusty, so if you've got asthma, chances are you're gonna die up there. And we'll be smelling it for weeks because, again, the air ducts aren't a secret escape hatch, they're how we ventilate the facility.");
        a.add("[throat clear] This thing on? I'm gonna be brief. Because I'm dying. Because I got shivved. A lot. I just wanna get it on record that using force fields for doors in a space prison is a bad idea. You know what would have been better? Regular doors. With locks. Locks that don't open when the power goes out. [cough cough] Man, those blue force fields looked good, though. Every time I saw one, I thought, Wow. I am in space. Still though. A door made out of paper would have been better in the long run. Would have at least slowed 'em down for a second. Anyway. [cough] Anybody not escaping or shivving me, get back to work.");
        a.add("(In alien voice)Those of you who volunteered to be injected with homo sapien DNA, I've got some good news and some bad news: bad news is we're postponing those tests indefinitely. Good news is we've got a much better test for you: fighting an army of man-mantises. Pick up a set of foreleg spurs, mesothorax armor and tubercle sheaths. You'll know when the test starts.");
        a.add("It's come to my attention that over half of our test subjects have only recently awoken from extended relaxation and were unaware that we're testing in space. So there it is: No conspiracy. No twist. We're in a test satellite orbiting the Earth. Commonly available information that absolutely anyone would have told you if you'd bothered to ask. Please stop forming groups of adventuring parties to uncover the big secret, because it's that we're in space.");
        a.add("Looks like we just had to seal up Science Sphere Seven. Hull breach. Another adventure party smashed through the hull to learn the big mystery. Guess they were busy doing that instead of testing, because I've mentioned we're in space every half hour. By the way: still in space.");
        a.add("Aaaand another hull breach. Let's all give a big hand to the test subjects of Sphere Eighteen for bravely uncovering the company-wide conspiracy, which is that there's no air in space. Once again: We're in space. It's not a secret. I am sincerely regretting my decision not to install windows in this thing.");
        a.add("Welcome, gentlemen, to the Aperture Hollow Science Jungle. Tramps, hillbillies, drifters: you're here because you followed the hobo signs. So, who is ready to scrounge around for some science? Now, you already met one another on the boxcar over here, so grab a bowl of slumgullion and a glass of sterno, and let me introduce myself. I'm Michigan Slim Cave Johnson. I'm the hobo king.");
        a.add("It's Cave. Greg's telling me the number of possible alternate universes is literally infinite. Maybe there's one where, I don't know, the Greeks won World War II. Just a heads up in case you get to a test chamber and find yourself surrounded by urns. Oh, Chariots!");
        a.add("[Shrieking sounds] That shrieking voice you just heard is the lovely Blark-Barg, my assistant. She's the backbone of this facility. Sorry fellas, she's married -- to producing seeds that germinate and detach from her exoskeleton at high speeds in search of human hosts! We keep her behind glass.");
        a.add("Hello, test subjects. Good news first: our telekinesis incubation program has been a huge success. Bad news: The candidate screening process was a lot less successful. Let me tell you, we picked a real bunch of smart alecs to give mind-powers to. You hear me? Stop blowing up heads. Actually, you know what? Negotiation's over. I'd like you all to meet Terry. He's -- [BLAM!] Real funny, guys. But the joke's on you. I taped all your paychecks to Terry's head. Ha! Why don't you put THAT in your head and blow it up?");
        a.add("That's right everybody, it's that time of year again: Happy Birth Day. You know the rules, everybody at the government-mandated maximum age needs to report to an ethnological redundancy associate toot suite. Looking through your files here--the following is a complete list of employees who need to snuff it. [coughs] Dorothy Russell, Age 98. End of list. Sorry about that, Dorothy. You had a good ninety-seven years, time to stop hoggin' all the resources. Leave some nutrient paste for the rest of us, why don't you. Cave Johnson, age fifty-one. We're done here.");
        a.add("Cave Johnson, junior claims representative for Aperture Science here. Well, former junior claims representative. Just found out I got laid off. Well, I'll just sneak into their recording office and let everyone know our president, that creep Doug Rattmann, is embezzling funds. Enjoy your Christmas bonuses knowing he took most of them, jerks.");
        a.add("Cave Johnson here. The mantis men have officially taken over the facility. If you can still get out, get out now! They're (crunching noises) oh god, they're breaking through the barricades!");
        a.add("Cave Johnson here. I seeeee you. I seeee your little feet. I'm gonna cut off your hair and put in on your feet and eat your little hair and feet! Um yum yum yum yum!");
        a.add("Hey! Hey! What are you doing in here? Beat it. [off mic] Come on, Greg, I told you not to let your creepy kid in my office. No, I'm sorry Greg, but there's something wrong with that kid. [putting on creepy kid voice] We'll test forever. Why's she whisper all time? [on mic] Hey, test subject, just keep going. Man, that kid's creepy.");
        a.add("Chariots! Cave Johnson here, reminding you to fill out the paperwork for full payment once you're done testing. The check may seem exorbitant, but you deserve it. Chariots!");
        a.add("Chariots! It's Cave Johnson. If you get through this next room, you'll get a bonus. And that's on top of the bonus I gave you this morning. [laughing] Don't thank me, because you're the real boss. Why? Because you teach me something new every day. Here's a third bonus. CHARIOTS! [getting choked up] You test subjects are the best. Oh my gosh, chariots...");
        a.add("This is Cave. PRIME. So apparently there's an alternate dimension Cave Johnson who just uses the word chariots for no reason. From now on, I'll say chariots twice if it's me. If you hear just one chariot, that's an alternate Cave. Chariot chariot.");
        a.add("Hello, test subject! Cave Johnson here, founder and CEO of Aperture Science: the best damn applied sciences company on Earth. How good is the science here? Get a load of this: I'm dead! Now, you're probably asking yourself, Cave, how is that possible? Are you some manner of Dracula? Or a Frankenstein? Or, depending on your cultural heritage, a Blackula or Latin Frankenstein? [chuckles] Nope! Just science. As of this morning, I have been resurrected inside of a computer. That aside, situation normal. So. Continue testing.");
        a.add("Just a warning to you test subjects: Greg and the boys told me that the massive influx of information I'd receive when they transferred my consciousness into a stadium-sized super computer would turn me crazy. So, once again a warning: Greg and the boys are no longer working here, so if they were doing something for you, that's not getting done.");
        a.add("Cave again. Now, I'll admit, losing my body does have its drawbacks. But it's got its perks too! As a being of pure intellect, I've now got time to read the entire literary canon of the human race. Here I go! [BEEP] And I am done. [sigh] Continue testing.");
        a.add("Pure Intellect Cave here. Not to brag, but while you were cat-assing that last test, I rewrote the collected works of everything ever. I figure,, if I gotta read this garbage for eternity, I may as well improve it. Next time you curl up with a time-honored classic and think to yourself, Man, I do not remember the Brothers Karamazov busting so many ghosts, you can thank yours truly.");
        a.add("Here's a question for you: Who is not afraid of no ghosts? [beep] As of just now, every character in every book by Virginia Woolf. Man, those things were dull.");
        a.add("Cave again. What is the one thing that could never ever ever ever in a million years get boring? If you said busting ghosts tragically, you'd be wrong. I was almost all the way through the W's when the bloom came off that rose. Heathcliff was defending Moonbase Wutherin Heights from the crafty poltergeist, when I realized exploring the vast realm of pure intellect is... boring. You know what I'd really like to do? Scratch my nose.");
        a.add("I've been thinking: What if Greg was right? What if injecting my consciousness into a computer robbed me of an eternal reward? Spiritually speaking. [beep] Alright, I just read up on it. Stumbled on a book about a fella who lived thousands of years ago. Sacrificed himself to save mankind. Went by the name of Hercules. Destroyed all the world's monsters so humans'd be safe, then went to Olympus for his trouble. Damn it, death was my monster! And I killed it! Where's my Olympus?");
        a.add("Unless... Aperture was the monster. Aperture and everybody inside it. Holy Hercules! I just thought of something. Keep testing. Or don't. Doesn't matter. I'll be back.");
        a.add("Whoa! Chariots chariots. For some reason, some of the audio was bleeding through in this universe. Don't know if you were catching the subtext there, but that computer Cave is crazy. So: Greg was right. As of now, we are cancelling the genetic lifeform disk operating system initiative. Boy, that could have backfired. Don't get cocky, Greg. There's an infinite number of universes where you weren't right, and I fired you an infinite number of times. Anyway, this Earth is far too dangerous and we are pulling you out. [pause] Right after this test.");
        a.add("Welcome, gentlemen, to Aperture Paranormal. Magicians, witches, crystal healing doctors: you're here because you have scary powers and we want in on it. So: who is ready to draw some pentagrams? Now you already met one another on the cab ride over so let me introduce myself. I'm Cave Johnson. I'm host to a tiny but powerful demon who lives in a secret place in my mouth.");
        a.add("Cave Johnson again, just a heads up, you are currently in a tiny test chamber floating around in my bloodstream. Remember, if you see a giant set of car keys, those are mine. Lab boys shrunk 'em part way down before I could stop 'em. No idea if it was for science or if they're just having one on at ol' Cave, but either way I'm you don't find those things pretty soon, I'm gonna have to call Triple A.");
        a.add("Hello, test subject. As you are no doubt aware, the President is being held hostage inside the giant super-prison on the floor of the Atlantic Ocean . Every science facility in America has been tasked with producing a Tough Guy capable of breaking into SuperMaxLantis. That's where YOU come in. I'm nominating myself and I'm gonna need some references. A test associate should be around soon to get a quote off you, so be as glowing as possible.");
        a.add("Quick update on all those pods we were finding in broom closets. Apparently some alien monster was body-snatching employees and spawning Communist replicas. The allegorical threat level on this one's through the roof. Actual threat level's pretty non-existent, though, so we've decided not to do anything about it. If the worst this thing can do is gestate glassy-eyed Yes Men, I say bring it on, Bug-Eyes. I got a whole list of troublemakers you can pod up any time you like.");
        a.add("Cave Johnson, new owner and CEO of Black Mesa. That's right, you've been bought. First order of business, we're renaming you under the Aperture brand. I'm leaning towards Blappeture Mesa. Marketing boys think something else. So: Blappeture it is. Next, they tell me you people are conducting some anomalous materials research that could result in a resonance cascade. So I'm shutting that down before you idiots end the world. A resonance cascade! You're supposed to be scientists. Use some common sense.");
        a.add("Cave Johnson here. Just wanted to let you know that, after decades of research and testing, we have finally transformed into beings of pure light. Go team. Not exactly what we were after, of course, but in the ballpark. So let's keep testing, and maybe someday we'll achieve man's ultimate dream: to evolve into pillars of pure salt. Can't wait. So salty.");
        a.add("Chariot chariot. By the way, you can make a bit of a mess in these rooms if you want. Scuff your shoes or stick gum on the walls, because these alternate Cave Johnsons are really cheesing me off.");
        a.add("Cave Johnson here. Just a heads-up we've got an interverse security breach in one of the test areas. You all enjoyed a good chuckle at Cave's expense when I started monitoring for parallel universe invasions. You all tried to stop me when I tried to garnish your wages to build defenses against said invasion. Succeeded too. So I hope you're happy, we've got a bogey from Earth-1 loose on the premises. Go write a letter to the Better Business Bureau about THAT, why don't you. Actually, don't.");
        a.add("Would anyone like to know what the invaders from Earth-1 are up to inside our facility? I don't blame you - bet it'd be fascinating stuff. But we don't have any multiverse invasion monitoring equipment. Asked for it. Told it was stupid. Anyway, I hope these monsters replace our air with chlorine - it'd finally give you crybabies something to cry about.");
        a.add("Just a quick update on the attack of the killer ants. Apparently they tried to commandeer the entirety of our nation's sugar reserves in Kentucky. Big firefight at Fort Sugar Knox. Edge-of-your-seat stuff. Anyway, that's as far as I made it through the movie before I fell asleep. So if anybody's seen Attack of the Killer Ants, don't spoil the ending or you're fired. By the way, chariots chariots.");
        a.add("Cavina Johnson here. It's come to my attention that one of you has sent a letter to the Supreme Council of Matriarchs accusing me of being a man. So, I want to assure both you and Gender Regulatory Committee that I am indeed one hundred percent all woman. And if you don't believe me, I swear to god I will beat you -- [off mic] What? [on mic] Greg tells -- [off mic] What? [on mic] Sally-Sue-Greg tells me we will all exchange handmade sympathy cards discussing how we feel about the issue. Alright, let's do some lady science!");
        a.add("I sincerely hope you're not allergic to air. Our peanut dust ventilator broke in this wing, so the atmosphere is only 60 per cent peanut dust.");
        a.add("Hey. It's me. The real me. Uh, chariots chariots. Anyway, it appears the test chambers in our dimension are being tested on. Looks like another alternate universe Cave Johnson is using the same trick I am. If you see that one, punch him in the throat for me. But make sure it's him and not me you're punching or you're fired.");
        a.add("Chariots chariots. We have a problem. That alternate Cave Johnson is using ALL our test chambers now. We have to take care of things here for a while, so you're on your own. Try to remember the tests so we can write it all down later.");
        a.add("Aha! We've got you, you...wait, is that the real you? From our dimension? Ahhh. Chariots chariots. It's Cave. Seriously, of all the infinite alternate dimensions, you happen to wind up randomly in ours again? Okay, just get through this test and be VERY careful not to mess anything up.");
        a.add("Hey. Chariots chariots. Just thought you should know, that sick boy from a couple of Earths ago? We kept monitoring that because, man, that was riveting. Anyway, he didn't make it. Good try, though. We were virtually all pulling for him.");
        a.add("Chariots chariots dammit! Now we've got two testers here from another damn Earth! We had one of 'em cornered, then the other one just portaled him out of there, then they high-fived and went their separate ways. I'm gonna need you to test double quick to make sure we're messing them up as badly as they're messing us up here.");
        a.add("Attention: Chariots chariots. There are at least six extra-dimensional testers here now, and to be honest, they're not even really testing anymore. They just all portaled in, made a human pyramid, ate my lunch and portaled out.");
        a.add("Chariots char-look it's me. Apparently, this other Earth has portal guns that can make portals on anything. We've had guys just walking along and suddenly, a portal opens beneath them and they fall out of a wall. I'm thinking maybe we should just work out a truce. I'll let you know if we can get in touch with this Evil Cave Johnson.");
        a.add("Chariots chariots. Okay. Greg managed to contact the Cave Johnson who keeps sending testers here and we've agreed, no more testing in each other's dimensions. We'll get you back here ASAP.");
        a.add("Hello, test subject. Just a heads-up that our research into stopping all the godzilla attacks on U.S. soil has been postponed indefinitely. Turns out it doesn't matter where you hatch a nest full of godzillas, they just make a beeline straight for Tokyo. [chuckles] Shoulda seen those things go. Anyway, crisis averted. Now everybody grab a dust pan and a broom, we gotta get rid of all these egg shells before the Nuclear Regulatory Commission shows up.");
        a.add("Break one-nine. Big Box Cave Johnson here, hauling a freight shaker with a loada cold ones in the wagon down to Texarkana. I got twenty-eight hours to get this done, so I'm putting the hammer down. Anybody hearing this, shake the bushes and gimme your ten-twenty. Also, test subjects, I'll be gone for twenty-eight hours, test on your own recognizance. I want to keep this channel clear, so do not use your CB radios. Cave Johnson, we're over and out here.");
        a.add("Greetings, friend. I'm Cave Johnson, CEO of Aperture Science. As you've no doubt learned after your time in cryosleep, human civilization as we knew it was utterly destroyed over a thousand years ago. We've attempted to rebuild as best we could with the only remaining book on the planet... [sigh] The Rock Says, the autobiography of Dwayne The Rock Johnson. So. Let's all pause for a moment to smell what the Rock was, is, and forever will be... cooking.");
        a.add("Chariots chariots. Whoever this alternate Cave Johnson is, he's a jerk. Instead of sending us the apology fruit assortment he promised, he just sent a whole bunch of angry wasps. We'll find a way to get back at him, don't you worry. You keep testing, and don't be afraid to get messy with it. We'll just see who wins this deadly game of cat and other cat.");
        a.add("Chariots chariots. Okay, now the other Cave has sent a huge block of frozen urine. It's too big for us to get it out of the multiverse device, so we just have to let it melt until we can wedge it out. Incidentally, if you come across a dimension where people eat nothing but asparagus, I'm guessing that's where our nemesis is, so keep your eyes peeled for that.");
        a.add("Cave Johnson here. I need you to - [Dark Cave] Do not listen to this man. He's the other Cave Johnson. He's an impostor! [Cave Prime] You're the impostor, impostor! Chariots chariots! [Dark Cave] Oh, yeah? Chariots chariots chariots! Just keep testing. I'll settle this. [Cave Prime] No, I'll settle this. [Dark Cave] Shut it, you. And you, keep testing!");
        a.add("All right. I think we shut down the impostor Cave's comlink. [Dark Cave] You'd like to think that, wouldn't you? [Cave Prime] Dammit! Stop imposting! [Dark Cave] Never! [Cave Prime] Oh, you stubborn, handsome devil.");
        a.add("It's come to my attention that there's a pair of sunglasses floating around this place that lets you see the subliminal propaganda we've painstakingly hidden on every visible surface. Look people, the reason motivational propaganda works is because you're not staring straight at it. That's the whole point. But what do I know? If everybody's too cool to be subliminally propagandized, feel free to wear your magic sunglasses all damn day. Motivate yourself from now on.");
        a.add("[laughter] Oh, Dark Cave, you are the only one around here who gets me. I tell you, I haven't had a conversation this damn good since... Hold on, I gotta talk to the help. [tap tap tap] Hey, you. Chariots chariots. Keep testing.");
        a.add("Hey, Dark Cave. [Dark Cave] Cave Prime! As I live and breathe methane. [Cave Prime] Listen, do you have a Greg in your universe? You want one! [laughter] Greg, come back! I wouldn't send you to Dark Cave Earth. [whispered] I would. Greg is on the table.");
        a.add("Cave Johnson here. Just a reminder that the core goal of Aperture Gas-Finding Science is to find gas, so make sure you let us know if you see any. If we meet our quarterly gas-finding target, I promise you we will don our bondage gear, fuel our death cars, and drive around in circles, whooping it up and shooting arrows at people. Who is ready to rule the wasteland? Alright, start looking.");
        a.add("Hello, test subject. Echo. Echo. Welcome to your first test. I'm your overseer, Cave Johnson, and I think, if you keep testing, you might find something very interesting about this planet. [chuckle] It's me. I'm the planet. You live on me. Wanted to save it till later, but man -- it's just too darn good. You really wouldn't have seen it coming. Do me a favor, don't tell any of the other test subjects. Also, don't pollute.");
        a.add("Chariots Chariots. According to Greg, theoretically, there's an Earth out there made entirely of money. Plus, since there's a infinite number of Earths, that means there's an infinite number of money planets. So I've done the math, and I figure the odds of finding this thing are one hundred percent. [off mic] Not now Greg! [on mic] That doesn't mean I want you to stop testing, but do keep an eye out for the money-verse. And let me be clear, I'm talking about U.S. currency. You find a peso-verse, you just keep walking.");
        a.add("Chariots Chariots chariots. Dark Cave here. Listen, you find the moneyverse, you bring it to me. I'll take care of you. You want to be promoted to head of testing? Done. You want your asparagus rations doubled? I'll pull some strings. You want all the methane you can breathe? Not a problem. Remember: Moneyverse. Dark Cave. Asparagus. Lots of it. Enough said.");
        a.add("Chariots chariots. Cave Prime here. I hear you've been brokering a deal with that other Cave. So here's what I want you to do: find your alternate self, steal his stuff, put in a box, and if there's a parking lot, walk the box out to it, because you're fired.");
        a.add("Chariots chariots. Cave Johnson here. Alright. Greg's informed this is not the best time to fire you. But, if you ARE talking to that other Cave, let me just remind you who you work for. [Dark Cave] Chariots chariots chariots. And let me remind you who's offering methane. [Cave Prime] Chariots chariots look, whatever he's offering, I'll double it. [off mic] Greg, how are we fixed for methane? Uh huh. Uh huh. Well, what do we use it all on? [Dark Cave] Dark Chariots. Evil Cave again. I think your choice is clear here. [Cave Prime] Test subject: not clear! Not clear! Keep testing!");
        a.add("Cave Prime here. [Dark Cave] Dark Cave here. [Cave Prime] While you were busy driving a wedge between us with your bidding war, Dark Cave's test subject found two moneyverse. And we're gonna split 'em. So there's no reason to offload our testing to alternate Earths anymore. Funding test chamber construction is no longer a problem. You know what else isn't a problem? Gold teeth. Greg, look at these choppers. Now show me yours. Man, you got tiny teeth Greg. The good news is, we're ready to start phase two: Figuring out a way to bring you back. Greg's gonna sink his weird little teeth into that problem toute suite. So, the next time you enter a test chamber, you'll back here on terra firma prime-a.");
        a.add("Hey Greg, it worked! Welcome back, test subject! Now get back to work. Just because we own a universe made of money, doesn't mean I'm made of money. Cave Johnson. We're done here.");
//Deleted and extended lines
//50s
        a.add("Now, the lab boys were adamant that I do not give you any hints on these tests. To be honest, they think I'm spoiling the results just by talking to you. Hizenstein Uncertainty Principles and so forth. I’ll give ‘em something more practical to be uncertain about. Their next paycheck. Anyway, overruled. If you think I'm affecting your decisions, in any way, don’t be afraid to speak up. I’m not made of glass. That reminds me: Caroline, Do we have a wing made out of glass yet? Let's get on that, Caroline.");
        a.add("Cave Johnson again. Just a heads-up: this next test’s dangerous. So if you get hurt, there’s a first aid station close by. Oh! Unless you’re participating in the double blind emergency treatment experiment. Then it’s just placebo first aid. Hold on, lemme check what test this is for… [pages flipping] Uh huh. Uh huh. No sir. I wouldn’t bother with it. What?");
        a.add("Caroline, do you think anyone’s gonna make it this far? Should I even bother making a message? What? Yes, I know how to turn it off. No, I don't want to turn it off... Alright, I feel like turning it off now.");
        a.add("If you’re hearing this, it means you’re taking a long time on the catwalks between tests. The lab boys say that might be a fear reaction. Well, as a wise man once said, “there’s nothing to fear but fear itself and maybe some mild to moderate jellification of bones.” Besides, to borrow from the voodoo sham known as “psychiatry,” it sounds to me like these eggheads are partaking in what they’d call “projection.” I'm no psychiatrist, but coming from a bunch of eggheads who never did anything more brave than boil some manganese - whatever the hell that accomplishes - that sounds like what they'd call \"projection.” THEY didn’t fly into space, storm a beach, or bring back the gold. No sir, we did! It's you and me against the world, son! I like your grit! Hustle could use some work, though. Now let’s solve this thing! Alright. Too much jawing, not enough testing. Let’s get some science done.");
        a.add("I'm no psychiatrist, but coming from a bunch of eggheads who never did anything more brave than read a big book – except for Greg who fought a bear once, but he’s not the point here – that sounds like what they'd call \"projection”.");
        a.add("Science isn't about WHY. It's about WHY NOT. Why is so much of our science dangerous? Why not marry safe science if you love it so much. In fact, why not invent a special safety door that won't hit you on the butt on the way out, because you are fired. Not you, son (\"test subject\" in-game), you're doing fine. Yes, you. Fired. Box. Your stuff. Out the front door. Parking lot. Car. Goodbye. Caroline, follow him out. Make sure he doesn’t cry all over the carpet.");
        a.add("Congratulations! You made it through. The simple fact that you’re standing here listening to me means you’ve made a glorious contribution to science. You’re a national hero. We're going to take your picture, so stand there and smile. Unless you were part of the Plaque Removing Deuterium Fluoride Laser test, in which case you might want to do us all a favor and keep your mouth closed until the bleeding stops. And don't worry: If you're one of our DNA test subjects, and you've got a hand for a face or whatnot, we’ll photograph you from the neck down. As founder and CEO of Aperture Science, I thank you for your participation and hope we can count on you for another round of tests. We’re planning some wonderful stuff with time travel. So if you never liked your father, why not come on back and try being him? We’re not gonna release this stuff into the wild until it’s good and damn ready, so as long as you keep yourself in top physical form, there’ll always be a limo waiting for you. Say goodbye, Caroline. She is a gem.");
//70s
        a.add("For many of you, I realize 60 dollars is an unprecedented windfall, so don’t go spending it all on… Caroline, what do these people buy? Tattered hats? Beard dirt? We’ve made some great advances since introducing our repulsion gel in the fifties, but you already know that, unless you’ve been living under a rock or something. Did we find any of these test subjects living under rocks? Perfect. So anyway. Welcome to Aperture. You’re here because we want the best, and… Caroline, really? This is it? And unfortunately, I guess you’re it.");
        a.add("So anyway. Welcome to Aperture. You’re here because we want the best test subjects sixty dollars can buy, and you’re apparently it.");
        a.add("Please help yourselves to the art on the wall. An eyeful. Don’t take it. Don’t take anything. It’s all nailed down. In fact, I take that back. Just get moving. Caroline, is the art nailed to the walls? Nevermind. Put more nails in it. Don’t get one of the lab boys to do it either. I want you to do it so it gets done right.");
        a.add("I know I said you could loiter for up to twenty minutes. That was a possibility, not a suggestion. You can move along any time. And for god’s sake, don’t touch the upholstery.");
        a.add("Well? Get moving. That sixty dollars isn’t hiding in here; it’s waiting for you at the other end of the enrichment sphere.");
        a.add("So, you might be wondering: why you? Simply: Human test subjects get better scientific results than animals. Why? For one, your tramps, lunatics, foundlings, what-have-you, can bring problem-solving ability to test environments with a facility that shames lower ruminants. For another, you have thumbs.");
        a.add("Great job, astronaut, war hero and/or Olympian! With your help, we’re gonna change the world! This on? [thump thump] Hey. Listen up down there. That thing up ahead’s called an elevator. Not a bathroom. [sigh] Caroline, has it really come to this? Damn it, you’re right. Damn good science, too. We’re not out of this race yet, Caroline.");
        a.add("In case you're interested, there're still some positions available for that bonus opportunity I mentioned earlier. Again: all you gotta do is let us disassemble you. We're not banging rocks together here. We know how to put a man back together. We'll take out any diseases we find in there, too, and replace all the organs that aren't tip top. So that's a complete reassembly. New vitals. Spit-shine on the old ones. Plus we're scooping out tumors. Frankly, you oughtta be paying us. Anyway, volunteers should line up outside Enrichment Sphere Archimedes Bravo.");
        a.add("Thank you – [off mic] I can’t believe I’m thanking these people [on mic] – for staggering your way through Aperture Science’s propulsion gel testing. You’ve made some real contributions to society for a change, and for that, humanity is grateful. If you had any belongings, please pick them up now. We don’t want old newspapers and sticks cluttering up the building. Once you’ve gathered your things, grab a compensation voucher, good for 60 dollars worth of stuff from the Aperture Science gift shop. Please only touch items you plan on purchasing. Thanks to the IRS and our patent-stealing competitors, there are parking meters in Duluth that earn more money than we do lately. So there’s no room in the budget to wash coffee mugs that you pick up and then decide not to buy. Caroline, put some extra security in the gift shop to make sure no one decides to take a nap in the t-shirt displays.");
//80s
        a.add("The bean counters told me we literally could not afford to buy seven dollars worth of moon rocks, much less seventy million. Bought ‘em anyway. Engineers said the moon rocks were too volatile to experiment on. Tested on ‘em anyway. Ground ‘em up, mixed em into a gel. And guess what? Ground up moon rocks are pure poison. I am deathly ill. Still, it turns out they’re a great portal conductor.");
        a.add("When you’re making some great science, it helps to keep a positive attitude. Look at Marie Curie. Invented radiology. Won two Nobel prizes. Dumb as a bag of hammers. Thought the light radiation gave off was pretty, walked around with it in bottles. Buried her with a smile on her face.");
        a.add("Let me tell you about a fella. Lived thousands of years ago. Only wanted folks to be a little nicer to each other. And in the end, he sacrificed himself to save us all. You know who I’m talking about: Hercules.");
        a.add("The point is: if we can store music on a compact disc, why can’t we store a man’s intelligence and personality on one? So I have the engineers figuring that out now. Brain Mapping. Artificial Intelligence. We should have been working on it thirty years ago. But I guess it’s too late for should haves and what ifs. I will say this - and I’m gonna say it on tape so everybody hears it a hundred times a day: if I die before you people can pour me into a computer, I want Caroline to run this place. (Now) she’ll argue. She’ll say she can’t. She’s modest like that. But you make her. Treat her just like you’d treat me. Hell, put her in my computer. I don’t care. Just make sure she’s taken care of. Allright, test’s over. You can head on back to your desk.");
//Miscellaneous tests
        a.add("Once upon a time there was a scorpion and a frog. The scorpion tells the frog “When I say ‘jump’ I don’t want to hear ‘how high?’ That means you’re not jumping!” Then the frog says “It’s my nature!” Well, be that as it may, we have a lot of tests to do and you are taking a long time on these catwalks and, yes, I broke out of the parable somewhere back there. But the point stands that you need to put some muscle back into your hustle, son.");
        a.add("This next test involves molecular dynamics. You’re gonna breathe in a bunch of tiny little robots, and they’re gonna optimize your DNA strands. Exciting stuff. Maybe nothing’ll happen. Or maybe you’ll have a big crab hand by the end of the test, or ten foot legs. It’s up to them. Trust me, I’m as anxious as you are to see how this plays out.");
        a.add("You might have noticed some safety warnings on the walls. Ignore ‘em. I keep telling the Bean Counters danger’s just a natural part of science, but boy they don’t want to hear it. Like telling a paradox to a robot – makes their heads explode.");
        a.add("That last test may have made your skeleton magnetic. I don’t know how. But if I were you, I wouldn’t stand next to any sheet metal.");
        a.add("Just a quick heads-up. If you suddenly find yourself able to excrete spider silk out of your fingers or the base of your spine, let one of the test associates know, cause that’s actually important.");
        a.add("The gel in this next test is probably going to make all of your skin solar-powered. Upside is, you’re not gonna get hungry. Ever. So if you were worried about your waistline, get this: You won’t be able to eat food even if you wanted to.");
        a.add("The gel in this next test’s gonna recalibrate your molecular whatsamacallits, blah blah blah. Bottom line is, you won’t need to go to the bathroom anymore. Your body’s just gonna process it up like anything else. Side effect might be that everything you eat from now on tastes like urine, though.");
        a.add("If you’re not a fan of the cartilage in your body, you are gonna love what this next test might do for you. Honestly, cartilage is like adenoids, or a second kidney. Body doesn’t want it, you don’t need it. Good riddance.");
        a.add("Ever wondered what a parallel universe you might be like? Well, stop wondering, because you’re just Hitler. Every parallel universe ever. You. Hitler. We can’t figure it out. Anyway, if you meet him in the next test, don’t kill him. I know, I know. But trust me, it’d be bad.");
        a.add("We’re gonna try and collapse three-dimensional space in this next test. We’re not gonna tell you when. Just give us a holler if everything starts looking flat.");
        a.add("While you’re completing this next test, we’re gonna test out a new device and see if we can read your thoughts. Don’t let it throw you. Just give us a nod if we’re getting close. You’re thinking about tungsten. Tungsten or zinc. Give us a wave if we nailed it. You’re thinking about the electrolytic production of hydrogen. How close is that? You’re thinking about the color green. Greenish blue. You might be wondering how I’m guessing what you’re thinking through a pre-recorded message. The answer: volume. I recorded a message for every word in the English language. Also: you are thinking about bib lettuce. Tell me I’m wrong. You’re still thinking about tungsten. I don’t blame you. It’s fascinating. Hey, Caroline. I think he’s thinking about you! Photosynthesis. That or fudge. The bacteria inside fudge. Nod your head if I’m getting close.");
        a.add("We’re gonna bombard you with a few rays in this next test. Nothing to be concerned about. We’re looking for bacterial contamination and inflammatory disease in your bowels. We put enough pathogens in the waiting room coffee to give diarrhea to an aircraft carrier, so if we don’t spot ‘em, I don’t know what to tell you.");
        a.add("Bonus test within a test in this next test: we hid a photon somewhere in here. You find it, it’s twenty grand in your pocket. You can keep the photon, too.");
        a.add("This next test might sunburn your eyes a little. Ask a test associate for some sunscreen you can put on your retinas if you think your eyes aren’t man enough to handle it.");
        a.add("The human body contains trace amounts of a whole hell of a lot of elements it doesn’t even seem to need. Copper, lead, silicon, cobalt, magnesium, carbon, oxygen. This next test, we’re gonna hit you with some microwaves and boil the worthless elements right out of you. Current hypothesis is it’s not even gonna break your stride. Honestly, what the hell has cobalt ever done for you? Good riddance.");
        a.add("With your help, we might eradicate heart and lung disease with this next test. Full disclosure: we’re going to achieve that by trying as hard as we can to make your heart and lungs stop working, then pump you full of some medicine we’ve been working on. Footnote to the disclosure: You’re incredibly brave and we’re proud of you.");
        a.add("Alright, this next test, I had to fight really hard for. None of the eggheads thought it was safe enough. I keep telling ‘em danger’s the best part of science, but they don’t want to hear it. It’s like telling a paradox to a robot: Makes their heads explode.");
        a.add("Alright, this next test, I had to fight really hard for. None of the eggheads thought it was safe enough. Did you? Ha. Caroline, watch this. You, stand next to him. You with the big head, over there. That’s right, all in a line against the wall. Okay, here we go. You’re fired you’re fired you’re fired you’re fired you’re fired.");
        a.add("Don’t eyeball me, son. Don’t snow me. I know an eyeball when I see one. It’s not good, wholesome eye-looking and I won’t stand for it. Eyeballs shouldn’t judge. They just send the information up for the brain to deal with. That’s the job. Get your eyes fixed, son. Caroline. Make appointments with all my engineers for eye surgery. Sign me up for it, too. From now on, everybody’s doing their eye-looking properly.");
        a.add("For this next test, we’ll be firing a few isotopes at your eyes to improve your night vision. If you feel a throbbing behind your eyes, that’s normal and should subside within a few hours. If you feel a pecking behind your eyes, that means a small bird got in there. We don’t know how it happens, but we’re working on it.");
        a.add("For this next test, you’ll be helping us solve the problem of male pattern baldness. If it works, you’re gonna start growing lush, new hair instantly. Downside: teeth hair.");
        a.add("How do you feel about your feet? Like ‘em? Good, because if this next test works, you’ll have five of ‘em.");
        a.add("You want to keep stealing my patents? Fine! This is war. Science war. The sweet science. You will cry into your evil black satin pillows about the day you messed with Cave Johnson! You hear me? I invented portals! I can put a doorway on the moon and another into your parking lot! Let’s see how many patents you steal when you’re floating around in outer space, you— What? Right. I know. Felt like having it on. How can… you tell? Fantastic. Good business. And if I wanted to turn it off— Good, good. Glad it was on. On purpose. And if I wanted to turn it off— Bam. Right. Good stuff, I like it. Let’s keep the switch. That’ll be all, Caroline. [click]");
        a.add("Caroline, hold my calls. I need to go see a man about a mule. What was that? Alright. Good. Mule. Gonna go see him in the bathroom. Back in ten.");
        return (a);
    }
}
